import{a as f,S as g,i as l}from"./assets/vendor-f736e62a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function y(s,o){try{return(await f.get("https://pixabay.com/api/",{params:{key:"43289261-b2f679df5fe28faf218337d96",q:s,image_type:"photo",orientation:"horizontal",captions:!0,page:o,per_page:15}})).data.hits}catch{throw new Error("Failed to fetch images from Pixabay API")}}function m(){const s=document.querySelector(".gallery");s.innerHTML=""}function p(s){const o=document.querySelector(".gallery");let a="";s.forEach(r=>{a+=`
      <a class="gallery__item" href="${r.largeImageURL}" target="_blank">
        <figure class="gallery__figure">
          <img class="gallery__img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
          <figcaption class="gallery__figcaption">
            <div class="gallery__caption">Likes: ${r.likes}</div>
            <div class="gallery__caption">Views: ${r.views}</div>
            <div class="gallery__caption">Comments: ${r.comments}</div>
            <div class="gallery__caption">Downloads: ${r.downloads}</div>
          </figcaption>
        </figure>
      </a>`}),o.innerHTML=a}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector("#search-form"),o=document.querySelector("#search-input"),a=document.querySelector(".gallery"),r=document.querySelector(".loader"),e=new g(".gallery a");let t=1,i="";async function d(){try{r.classList.add("visible");const n=await y(i,t);if(n.length===0){l.info({title:"Info",message:"No more images to load.",position:"topRight"});return}p(n),e.refresh(),t++}catch{l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{r.style.display="none"}}async function u(n){n.preventDefault();const c=o.value.trim();if(!c){l.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}m(),i=c,t=1,a.style.display="none",await d(),a.style.display="flex"}s.addEventListener("submit",u)});
//# sourceMappingURL=commonHelpers.js.map
