import{a as d,i as l}from"./assets/vendor-db34b893.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();async function f(a,s){try{return(await d.get("https://pixabay.com/api/",{params:{key:"43289261-b2f679df5fe28faf218337d96",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data.hits}catch{throw new Error("Failed to fetch images from Pixabay API")}}function u(){const a=document.querySelector(".gallery");a.innerHTML=""}function g(a){const s=document.querySelector(".gallery");let o="";a.forEach(r=>{o+=`
      <a class="gallery__item" href="${r.largeImageURL}" target="_blank">
        <figure class="gallery__figure">
          <img class="gallery__img" src="${r.webformatURL}" alt="${r.tags}" loading="lazy">
          <figcaption class="gallery__figcaption">
            <div class="gallery__caption">Likes: ${r.likes}</div>
            <div class="gallery__caption">Views: ${r.views}</div>
            <div class="gallery__caption">Comments: ${r.comments}</div>
            <div class="gallery__caption">Downloads: ${r.downloads}</div>
          </figcaption>
        </figure>
      </a>`}),s.innerHTML=o}document.addEventListener("DOMContentLoaded",()=>{const a=document.querySelector("#search-form"),s=document.querySelector("#search-input");document.querySelector(".gallery");const o=document.querySelector(".loader");let r=1,e="";async function t(){o.classList.add("visible");try{const i=await f(e,r);if(i.length===0){l.info({title:"Info",message:"No more images to load.",position:"topRight"});return}g(i),r++}catch(i){console.error("Error fetching images:",i),l.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{o.classList.remove("visible")}}async function n(i){i.preventDefault();const c=s.value.trim();if(!c){l.error({title:"Error",message:"Please enter a search term",position:"topRight"});return}u(),e=c,r=1,await t()}a.addEventListener("submit",n),new IntersectionObserver(async i=>{i[0].isIntersecting&&await t()},{threshold:0}).observe(o)});
//# sourceMappingURL=commonHelpers.js.map
